feat: Add github workflow for cron job in assigning reviewer to apps
hackutd/hackutd-24-site pull request #109
Opened 2024-10-11 14:26 UTC by uy-seng

Testing Locally,

1. Create firebase db, update `.env.local` and seed data into firebase using the script provided (in the attachments)
[scripts.zip](https://github.com/user-attachments/files/17343934/scripts.zip)

2. Install `act` and use `act workflow_dispatch --env-file ./.env.local` to test the workflow scripts.

2024-10-14 21:34 UTC, salmanjaher approved these changes
lgtm

2024-10-17 00:45 UTC, uy-seng commented on .github/workflows/assign-reviewers.yaml
> +    - cron: '0 0 * * *' # run cron job at midnight utc everyday
1-2am central time

2024-10-30 14:27 UTC, DedsecKnight requested changes

2024-10-30 14:27 UTC, DedsecKnight commented on .github/workflows/assign-reviewers.yaml
Remove this file please.

2024-10-31 00:08 UTC, merged